name: Create Magento 2 Module Artifacts on Release

on:
  release:
    types:
      - created

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4

      - name: Prepare Artifact Directory
        run: mkdir -p artifacts

      - name: Package EdgeDeliveryBridge Module
        run: |
          zip -r artifacts/EdgeDeliveryBridge.zip EdgeDeliveryBridge

      - name: Upload EdgeDeliveryBridge artifact
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: EdgeDeliveryBridge
          path: artifacts/EdgeDeliveryBridge.zip

      - name: Package EdgeDeliveryBridgeGraphQl Module
        run: |
          zip -r artifacts/EdgeDeliveryBridgeGraphQl.zip EdgeDeliveryBridgeGraphQl

      - name: Upload EdgeDeliveryBridgeGraphQl artifact
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: EdgeDeliveryBridgeGraphQl
          path: artifacts/EdgeDeliveryBridgeGraphQl.zip

      - name: Package EdgeDeliveryComponents Module
        run: |
          zip -r artifacts/EdgeDeliveryComponents.zip EdgeDeliveryComponents

      - name: Upload EdgeDeliveryComponents artifact
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: EdgeDeliveryComponents
          path: artifacts/EdgeDeliveryComponents.zip

      - name: Package EdgeDeliveryGraphQl Module
        run: |
          zip -r artifacts/EdgeDeliveryGraphQl.zip EdgeDeliveryGraphQl

      - name: Upload EdgeDeliveryGraphQl artifact
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: EdgeDeliveryGraphQl
          path: artifacts/EdgeDeliveryGraphQl.zip
