name: Archive Multiple Folders on Release

on:
  release:
    types:
      - created

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive EdgeDeliveryBridge
        run: |
          mkdir -p archives
          zip -r archives/EdgeDeliveryBridge.zip EdgeDeliveryBridge

      - name: Archive EdgeDeliveryBridgeGraphQl
        run: |
          zip -r archives/EdgeDeliveryBridgeGraphQl.zip EdgeDeliveryBridgeGraphQl

      - name: Archive EdgeDeliveryComponents
        run: |
          zip -r archives/EdgeDeliveryComponents.zip EdgeDeliveryComponents

      - name: Archive EdgeDeliveryGraphQl
        run: |
          zip -r archives/EdgeDeliveryGraphQl.zip EdgeDeliveryGraphQl

      - name: Upload archives as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: EdgeDeliveryArchives
          path: archives/*.zip
