name: Create Magento 2 Module Artifacts on Release

on:
  release:
    types:
      - created

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Artifact Directory
        run: mkdir -p artifacts

      - name: Package EdgeDeliveryBridge Module
        run: |
          zip -r artifacts/EdgeDeliveryBridge.zip EdgeDeliveryBridge

      - name: Package EdgeDeliveryBridgeGraphQl Module
        run: |
          zip -r artifacts/EdgeDeliveryBridgeGraphQl.zip EdgeDeliveryBridgeGraphQl

      - name: Package EdgeDeliveryComponents Module
        run: |
          zip -r artifacts/EdgeDeliveryComponents.zip EdgeDeliveryComponents

      - name: Package EdgeDeliveryGraphQl Module
        run: |
          zip -r artifacts/EdgeDeliveryGraphQl.zip EdgeDeliveryGraphQl

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Upload EdgeDeliveryBridge to Release
        run: gh release upload ${{ github.event.release.tag_name }} artifacts/EdgeDeliveryBridge.zip --repo ${{ github.repository }}

      - name: Upload EdgeDeliveryBridgeGraphQl to Release
        run: gh release upload ${{ github.event.release.tag_name }} artifacts/EdgeDeliveryBridgeGraphQl.zip --repo ${{ github.repository }}

      - name: Upload EdgeDeliveryComponents to Release
        run: gh release upload ${{ github.event.release.tag_name }} artifacts/EdgeDeliveryComponents.zip --repo ${{ github.repository }}

      - name: Upload EdgeDeliveryGraphQl to Release
        run: gh release upload ${{ github.event.release.tag_name }} artifacts/EdgeDeliveryGraphQl.zip --repo ${{ github.repository }}
