name: Create Magento 2 Module Artifacts on Release

on:
  release:
    types:
      - created

permissions:
  contents: write  # Ensure the GITHUB_TOKEN has write permissions for contents

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Artifact Directory
        run: mkdir -p artifacts

      - name: Package EdgeDeliveryBridge Module
        run: |
          zip -r artifacts/EdgeDeliveryBridge.zip EdgeDeliveryBridge

      - name: Package EdgeDeliveryBridgeGraphQl Module
        run: |
          zip -r artifacts/EdgeDeliveryBridgeGraphQl.zip EdgeDeliveryBridgeGraphQl

      - name: Package EdgeDeliveryComponents Module
        run: |
          zip -r artifacts/EdgeDeliveryComponents.zip EdgeDeliveryComponents

      - name: Package EdgeDeliveryGraphQl Module
        run: |
          zip -r artifacts/EdgeDeliveryGraphQl.zip EdgeDeliveryGraphQl

      - name: Upload EdgeDeliveryBridge to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/EdgeDeliveryBridge.zip
          tag: ${{ github.event.release.tag_name }}

      - name: Upload EdgeDeliveryBridgeGraphQl to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/EdgeDeliveryBridgeGraphQl.zip
          tag: ${{ github.event.release.tag_name }}

      - name: Upload EdgeDeliveryComponents to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/EdgeDeliveryComponents.zip
          tag: ${{ github.event.release.tag_name }}

      - name: Upload EdgeDeliveryGraphQl to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/EdgeDeliveryGraphQl.zip
          tag: ${{ github.event.release.tag_name }}
