name: Create Magento 2 Module Artifacts on Release

on:
  release:
    types:
      - created

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Artifact Directory
        run: mkdir -p artifacts

      - name: Package EdgeDeliveryBridge Module
        run: |
          zip -r artifacts/EdgeDeliveryBridge.zip EdgeDeliveryBridge

      - name: Package EdgeDeliveryBridgeGraphQl Module
        run: |
          zip -r artifacts/EdgeDeliveryBridgeGraphQl.zip EdgeDeliveryBridgeGraphQl

      - name: Package EdgeDeliveryComponents Module
        run: |
          zip -r artifacts/EdgeDeliveryComponents.zip EdgeDeliveryComponents

      - name: Package EdgeDeliveryGraphQl Module
        run: |
          zip -r artifacts/EdgeDeliveryGraphQl.zip EdgeDeliveryGraphQl

      - name: Upload EdgeDeliveryBridge to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/EdgeDeliveryBridge.zip
          asset_name: EdgeDeliveryBridge.zip
          asset_content_type: application/zip

      - name: Upload EdgeDeliveryBridgeGraphQl to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/EdgeDeliveryBridgeGraphQl.zip
          asset_name: EdgeDeliveryBridgeGraphQl.zip
          asset_content_type: application/zip

      - name: Upload EdgeDeliveryComponents to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/EdgeDeliveryComponents.zip
          asset_name: EdgeDeliveryComponents.zip
          asset_content_type: application/zip

      - name: Upload EdgeDeliveryGraphQl to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/EdgeDeliveryGraphQl.zip
          asset_name: EdgeDeliveryGraphQl.zip
          asset_content_type: application/zip
